server:
  port: 8080
  address: 127.0.0.1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /api/auth-service/v3/api-docs
      - name: Profile Service
        url: /api/profile-service/v3/api-docs
      - name: Product Service
        url: /api/product-service/v3/api-docs
      - name: Cart Service
        url: /api/cart-service/v3/api-docs
      - name: Order Service
        url: /api/order-service/v3/api-docs
      - name: Offer Service
        url: /api/offer-service/v3/api-docs
      - name: Payment Service
        url: /api/payment-service/v3/api-docs
      - name: Search Service
        url: /api/search-service/v3/api-docs
      - name: Notification Service
        url: /api/notification-service/v3/api-docs
    disable-swagger-default-url: true

spring:
  main:
    web-application-type: reactive
  reactor:
    context-propagation: auto
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/product-service/**
              filters:
                - StripPrefix=2
                - UserContext
            - id: cart-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/cart-service/**
              filters:
                - StripPrefix=2
                - UserContext
            - id: profile-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/profile-service/**
              filters:
                - StripPrefix=2
                - UserContext
            - id: order-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/order-service/**
              filters:
                - StripPrefix=2
                - UserContext
            - id: offer-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/offer-service/**
              filters:
                - StripPrefix=2
                - UserContext

            - id: payment-service
              uri: http://localhost:8086
              predicates:
                - Path=/api/payment-service/**
              filters:
                - StripPrefix=2
                - UserContext

            - id: search-service
              uri: http://localhost:8087
              predicates:
                - Path=/api/search-service/**
              filters:
                - StripPrefix=2
                - UserContext
                
            - id: notification-service
              uri: http://localhost:8090
              predicates:
                - Path=/api/notification-service/**
              filters:
                - StripPrefix=2
                - UserContext

            - id: auth-service
              uri: http://localhost:8088
              predicates:
                - Path=/api/auth-service/**
              filters:
                - StripPrefix=2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://loomandlume.shop

frontend:
  url: https://loomandlume.shop

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
