export const en = {
    logoName: "Loom&Lume",
    commonPageTitle: "Loom&Lume - Luxury Handmade Candle Store",
    logoTagline: "Where Craft Meets Light.",
    appDescription: "Luxury handcrafted candles inspired by calm.",
    account: "Account",
    hi: "Hi",
    copyrightText: "© Loom&Lume 2025. All rights reserved.",
    footerNote: 'Handcrafted candles that illuminate your life with captivating scents and serene ambience.',
    myWishlist: "My Wishlist",
    myCart: "My Cart",
    store: "store",
    about: "about",
    readStories: "Read Stories",
    customCandles: "custom candles",
    category: "Category",
    social: "Social",
};
