export const en = {
  logoName: "Loom&Lume",
  commonPageTitle: "Loom&Lume - Luxury Handmade Candle Store",
  logoTagline: "Where Craft Meets Light.",
  appDescription: "Luxury handcrafted candles inspired by calm.",
  account: "Account",
  hi: "Hi",
  copyrightText: "© Loom&Lume 2025. All rights reserved.",
  footerNote:
    "Handcrafted candles that illuminate your life with captivating scents and serene ambience.",
  myWishlist: "My Wishlist",
  myCart: "My Cart",
  store: "store",
  about: "about",
  readStories: "Read Stories",
  customCandles: "custom candles",
  category: "Category",
  social: "Social",
  manageProfile: "Manage Profile",
  savedAddesses: "Saved Addresses",
  orderHistory: "Order History",
  signout: "Sign out",
  newlyAddedItems: "Newly Added Items",
  newlyAddedItemsDesc: "Check the latest items through out the website",
  mostLovedItems: "Most Loved Items",
  mostLovedItemsDesc: "Check the most loved items by our customer",
  welcome: "Welcome",
  testimonials: "Testimonials",
  fastShipping: "Fast Shipping",
  freeAndFastShipping: "Free and Fast Shipping",
  freeEasyReturns: "Free Easy Returns",
  returnIn6Days: "Return in 6 days",
  fastDelivery: "Fast Delivery",
  getProductUnder24hrs: "Get product under 24hrs",
  allDaySupport: "All Day Support",
  supportCare: "24/7 support care",
  securePayments: "Secure Payments",
  razorPayProtect: "100% protected by RazorPay",
  trending: "Trending",
  exploreTrendingProducts: "Explore Trending Products",
  exploreTrendingProductsDesc:
    "We've curated some of our latest and most purchased products in emoni scents. Buy now and get a huge discount",
};
